#!/bin/bash
usage="$0 [-p <prefix>] [-s <snap_prefix>]"
PType="repo"
Prefix="testing"
UpdateArg="update"

source $(dirname $(readlink -f $0))/.common-lunarg.sh

while getopts ":p:s:" options; do
    case $options in
	p ) Prefix=$OPTARG;;
	s ) PType="snapshot"
	    UpdateArg="switch"
	    SPrefix=$OPTARG;;
	* ) echo $usage
	    exit 1;;
    esac
done

for Distro in "${LunarGDistros[@]}";
do
    if [ "${PType}" == "snapshot" ]; then
        Snapshot=${Distro}_${SPrefix:-$Prefix}
    fi
    # Update if it's already published
    if aptly publish -raw=true list 2> /dev/null | grep -q -e "^vulkan/${Prefix} ${Distro}$"; then
        echo "*** Publishing update to vulkan/${Prefix} ${Distro}"
	aptly publish ${UpdateArg} \
	    -gpg-key="${LunarGGPGKey}" \
	    ${Distro} vulkan/${Prefix} ${Snapshot:-}
    else
        echo "*** Publishing to newly created vulkan/${Prefix} ${Distro}"
	aptly publish ${PType} \
	    -gpg-key="${LunarGGPGKey}" \
	    -label="LunarG Vulkan Package ${Distro} Repository"\
	    -origin="vulkan.lunarg.com"\
	    ${Snapshot:-$Distro} vulkan/${Prefix}
    fi
done
