#!/bin/bash
usage="Usage: $(basename $0) -c COMMIT_ID [-i] [-n] [-b BUILD_NUMBER] [-t TEMP_BRANCH] [-s BUILD_SUFFIX] [-d DEBIAN_PACKAGING_VERSION]"

commitID=""
buildNum="1"
debVers="1"
buildSuffix="~autobuild"
tempBranch="build"
interactive=""
noBuild=""
while getopts ":c:b:t:s:d:in" options; do
    case $options in
	c ) commitID="${OPTARG}";;
	b ) buildNum="${OPTARG}";;
	t ) tempBranch="${OPTARG}";;
	s ) buildSuffix="${OPTARG}";;
	d ) debVers="${OPTARG}";;
	i ) interactive="TRUE";;
	n ) noBuild="TRUE";;
	* ) echo $usage
	    exit 1;;
    esac
done

if [ -z "$commitID" ]; then
    echo $usage
    exit 1
fi

git reset --hard
git clean -f
git checkout -B ${tempBranch}
git reset --hard ${commitID}
git checkout debian-unstable -- debian
cimsg="merge debian packaging"
if [ "$interactive" ]; then
    cimsg=$(zenity --entry \
    --title="Add Debian packaging" \
    --text="Enter a comment for this commit" \
    --entry-text="$cimsg")
fi
if [ ! -z "$cimsg" ]; then
    git commit -m "$cimsg"
else
    exit 1
fi
cimsg="merge debian-unstable branch to connect histories"
if [ "$interactive" ]; then
    cimsg=$(zenity --entry \
    --title="debian-unstable branch merge" \
    --text="Enter a comment for this commit   " \
    --entry-text="$cimsg")
fi
if [ ! -z "$cimsg" ]; then
    git merge debian-unstable -s ours -m "$cimsg"
else
    exit 1
fi

newVersion="$($(dirname $(readlink -f $0))/generate-version-string -v)"

if [ "$interactive" ]; then
    newVersion=$(zenity --entry \
	    --title="Version String" \
	    --text="Verify/modify Version string for this build" \
	    --entry-text="$newVersion")
fi
if [ ! -z "$newVersion" ]; then
    echo "Building Package Version: $newVersion"

    # Update changelog:
    cimsg="Automated package build"
    if [ "$interactive" ]; then
	cimsg=$(zenity --entry \
	--title="update debian/changelog" \
	--text="Enter a comment for the changelog" \
	--entry-text="$cimsg")
    fi
    if [ ! -z "$cimsg" ]; then
	dch -r --distribution=unstable ""
	dch --newversion "${newVersion}-${debVers}" "$cimsg"
    else
	exit 1
    fi

    # Commit changelog and kick off a build..
    if [ -z "$noBuild" ]; then
	git add debian/changelog
	git commit -m "$cimsg"
	cowbuild-package-lunarg -b "${buildNum}" -s "${buildSuffix}"
    fi
fi
