#!/bin/sh
sudo DIST=bionic ARCH=amd64 cowbuilder --update
sudo DIST=xenial ARCH=amd64 cowbuilder --update
#sudo DIST=xenial ARCH=i386 cowbuilder --update
sudo DIST=stable ARCH=amd64 cowbuilder --update
#sudo DIST=stable ARCH=i386 cowbuilder --update
