#!/bin/bash
usage="$0 [-b <build version>]"

while getopts ":b:" options; do
    case $options in
	b ) BUILD_VERSION="${OPTARG}.";;
	* ) echo $usage
	    exit 1;;
    esac
done

SOURCE=$(dpkg-parsechangelog | sed -n 's/^Source: //p')
BASE_VERSION=$(dpkg-parsechangelog | sed -n 's/^Version: //p' | sed -n 's/-.*$//p')
PKG_ARCH=$(sed -n 's/^Architecture: //p' debian/control)
BUILD_VERSION="0."

cowbuild_package () {
    DIST=$1
    VENDOR=$2
    LOCAL=$3
    OPTS=${4:-""}

    git reset --hard
    rm -f "../${SOURCE}_${BASE_VERSION}-*"
    dch --vendor=$VENDOR --local=$LOCAL ""
    dch --vendor=$VENDOR --distribution=$DIST --release ""
    debuild -i -us -uc -sa -S --lintian-opts -X chng
    FULL_VERSION=$(dpkg-parsechangelog | sed -n 's/^Version: //p')
    DSC_FILE="../${SOURCE}_${FULL_VERSION}.dsc"
    if [[ $PKG_ARCH =~ "amd64" ]] || [[ $PKG_ARCH =~ "all" ]] || [[ $PKG_ARCH =~ "any" ]] ; then
	echo "#########################################################"
	echo "Building amd64 $DIST packages.."
	echo "#########################################################"
	sudo DIST=$DIST ARCH=amd64 cowbuilder --pkgname-logfile --build $OPTS $DSC_FILE
    fi
#    if [[ $PKG_ARCH =~ "i386" ]] || [[ $PKG_ARCH =~ "any" ]] ; then
#	echo "#########################################################"
#	echo "Building i386 $DIST packages.."
#	echo "#########################################################"
#	# Don't rebuild the source package, only binary.
#	sudo DIST=$DIST ARCH=i386 cowbuilder --binary-arch --pkgname-logfile --build $DSC_FILE
#    fi
}

# Check all the normal sources for an orig tarball before generating a new one
# (which likely will have a different hash than a pre-existing original)
origtargz -dt
if [ $? -ne 0 ]; then
    debian/rules gentarball
fi

source $(dirname $(readlink -f $0))/.common-lunarg.sh
for Distro in "${LunarGDistros[@]}";
do
    cowbuild_package ${Distro} ${DistroVendor[${Distro}]} \
                     "${DistroLocalSuffix[${Distro}]}${BUILD_VERSION}" \
                     "${DistroPbuilderOpts[${Distro}]}"
done
