#!/bin/bash
source $(dirname $(readlink -f $0))/.common-lunarg.sh
for Distro in "${LunarGDistros[@]}";
do
    sudo DIST=${Distro} ARCH=amd64 cowbuilder --update
    #sudo DIST=${Distro} ARCH=i386 cowbuilder --update
done
