#!/bin/sh

for file in /var/cache/pbuilder/stretch-*/result/*.changes; do
	reprepro -Vb . include stable $file;
done

for file in /var/cache/pbuilder/xenial-*/result/*.changes; do
	reprepro -Vb . include xenial $file;
done

